### ISSUE TITLE
Commands not reaching HABPanelViewer - possibly losing connection

### ISSUE THREAD

**Issue by smar000** [vbier/habpanelviewer#10]
Continuing from the discussion in the main openHAB thread https://community.openhab.org/t/habpanelviewer/34112/210?u=smar

Commands do not seem to be consistently getting through to HABPanelViewer. This may be because HABPanelViewer loses its connected status from time to time. I had originally though that this only happened when the device (Amazon Fire 7, 7th gen tablet) went to sleep, but this may not necessarily be the case. In the attached logs (from the latest test build, Version 0.9.14pre, build 23 Jan 2018 3:48:55pm), HABPanelViewer continued to show that it was connected after coming out of standby. However, it did not respond to any changes in the designated openHAB Command Item, and a minute or so later (without the device going into standby mode again), changed its status to "not connected". Command log on HABPanelViewer remains empty.

**Comment by vbier** [comment]
I am not sure what is going on in your network. The logfile shows 33 connection losses and subsequent reconnects reported by chrome.
The SSE library that I use for the connection does not report any connection loss at all. I will check if I can find out what the problem in the lib is.

**Comment by smar000** [comment]
That's very odd. Network connection on the devices seem fine, even when HABPanelViewer shows not connected. Generally it seems to be issues with just commands getting through - the HABPanel dashboards themselves seem to work fine and widgets correctly show status updates.

**Comment by vbier** [comment]
Can you test if https://github.com/vbier/habpanelviewer/raw/issue10/app-debug.apk improves things?

**Comment by smar000** [comment]
From a very quick test, this does seem to be holding the connection better - I haven't yet seen the "not connected" message in the last 15 minutes or so (whereas previously I would get it within a couple of minutes).

However, the commands are still not properly getting through. I sent a number of SCREEN_DIM and SCREEN_ON commands. The first 3 of these went through (and the command log shows them correctly). After that, nothing seems to be getting through, e.g. towards the end of the attached logs, a number of commands were sent which did not get through.

[logcat8.log](https://github.com/vbier/habpanelviewer/files/1667586/logcat8.log)

**Comment by vbier** [comment]
I once again updated the apk and tried to improve state handling and reconnect. This is supposed to be a little bit rough, it is just to see if upgrading to a newer netty version brings any benefits regarding the connection. If we see this is better, I will have to take the time to make and improve code quality and robustness.

Can you please retest?

**Comment by smar000** [comment]
Thanks for this. It seems to perform slightly better than the previous build in that more commands get through initially before they stop.

However, one thing I've found is that when commands stop getting through,  the stoppage is only for a period of time, e.g. anything from 15 to 20 seconds to a couple of minutes, before they start getting through again. Not sure if the system is reconnecting in the background during this period or is it possible that the issue may be in the received command processing part of the app?

Thanks again for all your perseverance on this - much appreciated!

**Comment by vbier** [comment]
During the time when no command get through, does the menu show connected or not connected? Can you please add a log once again?

**Comment by smar000** [comment]
The menu shows connected for a period of time when I go back from the command window but then interestingly shows "not connected" quickly followed by connected. Commands then go through again. Attached log covers such a period.

[logcat10.log](https://github.com/vbier/habpanelviewer/files/1677619/logcat10.log)

**Comment by vbier** [comment]
The last log looks like it is holding the connection and getting the commands, but then fails to process them with an exception. The app has no registered listeners for the command item, which it should have. I have added some more logging in order to find the reason for this. Can you please generate another log?

**Comment by smar000** [comment]
Sure, log attached.

[logcat11.log](https://github.com/vbier/habpanelviewer/files/1678398/logcat11.log)

**Comment by vbier** [comment]
This log does once again show a connection drop. It looks like commands TEST2 and TEST3 have been missed. Connection goes away before command TEST2, browser connection returns afterwards and receives TEST3, SSE connection is reestablished after that.

So the browser misses TEST2,
SSE misses TEST2 and TEST3.

Unfortunately there are no timestamps in the log, the SSE connection should try to reconnect with a 2 second interval, the browser connection with a 5 second interval. But as I already wrote, browser reconnects before SSE.

I have now added more logging to the reconnect. Can you generate another log with 
`adb logcat -v threadtime`
so that I also get timestamps?

**Comment by smar000** [comment]
Log attached with timestamps. 

One thing I noticed both this time and the previous time was that even for the first command, I had to retry multiple times - i.e. there was a long pause before commands started. 

Also any thoughts on why it shows the connection drops? In the past when I checked, even when the connection status showed not connected, HABPanel widget updates were coming through correctly, which would indicate that the Kindle itself was not dropping its wifi connection - at least not that I could tell from a user experience perspective.

[logcat12.log](https://github.com/vbier/habpanelviewer/files/1679096/logcat12.log)

**Comment by vbier** [comment]
There are three SSE disconnects in the log file. WIFI is working all the time, I have no idea why the connection is dropped.

If you check the log, you find the three browser disconnects;
```
01-30 19:22:47.965  5724  5724 I chromium: [INFO:CONSOLE(226)] "SSE error, closing EventSource", source:  (226)
01-30 19:23:49.749  5724  5724 I chromium: [INFO:CONSOLE(226)] "SSE error, closing EventSource", source:  (226)
01-30 19:24:47.495  5724  5724 I chromium: [INFO:CONSOLE(226)] "SSE error, closing EventSource", source:  (226)
```

If you look at the timestamps, these happen nearly every minute, which most likely is no coincidence.
After every of these disconnects you can see one of my log messages at the earliest possible point, when reading from the SSE connection:
```
01-30 19:22:48.547  5724  5911 V Habpanelview: SSE onLogMessage: channelRead0: status = 200, headerDone=true, line=0
01-30 19:23:49.796  5724  6225 V Habpanelview: SSE onLogMessage: channelRead0: status = 200, headerDone=true, line=0
01-30 19:24:49.312  5724  6259 V Habpanelview: SSE onLogMessage: channelRead0: status = 200, headerDone=true, line=0
```

After that it takes around 30 seconds until the library realizes that the connection is gone and starts to reconnect. Normally, instead of the 0, there is a hex number indicating the size of the following message. In my network, I have never seen the 0. I will have to check openHAB code to see if is expected to get a 0 size message.

Are you using a reverse proxy in front of your openHAB machine or are you directly connected?

**Comment by vbier** [comment]
As it looks like I can not do anything about the connection loss, I tried something else. I have now added code that listens for the browser messages and triggers a reconnect when the browser sse connection disconnects. With a little luck, this keeps the times the app is disconnected to a minimum.

You can find the apk here: https://github.com/vbier/habpanelviewer/raw/issue10-2/app-debug.apk

**Comment by vbier** [comment]
Can you add a log file so I can check that you had a connection loss and see reconnect did really happen?

**Comment by smar000** [comment]
Sure, attached.

[logcat14.log](https://github.com/vbier/habpanelviewer/files/1686351/logcat14.log)

**Comment by vbier** [comment]
I have pushed the fix to the rewriteControlCode branch. Note that the functionality has to be enabled in the settings. It is called "Track Browser Connection".

**Comment by Webfeger** [comment]
![c0b2f1f3-83dc-444c-99df-b912d605430b](https://user-images.githubusercontent.com/37270376/38458320-567e84bc-3a9d-11e8-8996-9d415f1ae2c9.jpeg)
Issue still exist..

**Comment by vbier** [comment]
This is something completely different. What you see in your screenshot has nothing to do with the SSE connection this issue is about.

**Comment by Webfeger** [comment]
thats a little bit strange because i couldn‘t find the reason.. 
i try to reset this device..

**Comment by Webfeger** [comment]
lol i post my screenshot in wrong thread. i delete it.
